Update text for slash command
Heanthor/auctioneer-bot pull request #113
Opened 2022-02-22 02:15 UTC by unlockedSound

Adds text updates for slash commands.

2022-02-22 04:51 UTC, Heanthor requested changes

2022-02-22 04:51 UTC, Heanthor commented on internal/handlers/api/routes.go
> +				r.Get("!bg", a.BuyersGuide)
please revert this

2022-02-22 04:51 UTC, Heanthor commented on internal/handlers/handlers.go
> +	msg += "\t**/bg+**: Print an extended Buyer's Guide report on a craftable item, which includes all intermediary prices.\n"
This is `/buyers-guide`

2022-02-22 04:51 UTC, Heanthor commented on internal/handlers/priceHandlers.go
> +		resp.Message = "Error retrieving choice, try again or type `/clear`."
I don't like `type` anymore, could this be `run` or `use`?

2022-02-22 04:51 UTC, Heanthor commented on internal/handlers/shoppingListHandlers.go
> +	msg += "_Example:_ `/shopping-list item add` `item:`flask of power `price:`500g.\n\n"
The ticks here don't look right

2022-02-22 04:51 UTC, Heanthor commented on internal/handlers/shoppingListHandlers.go
> +// 	msg += "To change options for this list, use `/shopping-list options`.\n"
Just leave this in, I will fix it before shipping

2022-02-22 04:51 UTC, Heanthor commented on internal/handlers/shoppingListHandlers.go
> +		return &transport.Response{Message: "You have no active shopping list. Create one first with \"/shopping-list show\"."}, nil
Could you pull this error message into a variable so that it's not duplicated 4 times?

2022-02-27 04:54 UTC, Heanthor commented on internal/handlers/handlers.go
> +	msg += "\t**/bg+**: Print an extended Buyer's Guide report on a craftable item, which includes all intermediary prices.\n"
@joseph3114

2022-02-27 04:54 UTC, Heanthor commented on internal/handlers/shoppingListHandlers.go
> +	msg += "_Example:_ `/shopping-list item add` `item:`flask of power `price:`500g.\n\n"
@joseph3114

2022-02-27 17:25 UTC, unlockedSound commented on internal/handlers/shoppingListHandlers.go
> +	msg += "_Example:_ `/shopping-list item add` `item:`flask of power `price:`500g.\n\n"
What's off with them. I know it might look odd but tried to mimic the behavior that a user sees as they enter the slash command

2022-02-28 01:17 UTC, Heanthor commented on internal/handlers/shoppingListHandlers.go
> +	msg += "_Example:_ `/shopping-list item add` `item:`flask of power `price:`500g.\n\n"
Ah I see. Can you post a screenshot of what it looks like rendered?

2022-04-10 01:28 UTC, merged